package org.garen.oss.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class File implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.name
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.suffix
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String preview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.min_md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String minMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.min_preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private String minPreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.create_time
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.name
     *
     * @return the value of file.name
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.name
     *
     * @param name the value for file.name
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.md5
     *
     * @return the value of file.md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.md5
     *
     * @param md5 the value for file.md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.suffix
     *
     * @return the value of file.suffix
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.suffix
     *
     * @param suffix the value for file.suffix
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.preview
     *
     * @return the value of file.preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getPreview() {
        return preview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.preview
     *
     * @param preview the value for file.preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setPreview(String preview) {
        this.preview = preview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.min_md5
     *
     * @return the value of file.min_md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getMinMd5() {
        return minMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.min_md5
     *
     * @param minMd5 the value for file.min_md5
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setMinMd5(String minMd5) {
        this.minMd5 = minMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.min_preview
     *
     * @return the value of file.min_preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public String getMinPreview() {
        return minPreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.min_preview
     *
     * @param minPreview the value for file.min_preview
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setMinPreview(String minPreview) {
        this.minPreview = minPreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.create_time
     *
     * @return the value of file.create_time
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.create_time
     *
     * @param createTime the value for file.create_time
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}