context:
  listener:
    classes: org.garen.oss.startup.InitTypeCache

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.garen.oss.mybatis.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.170.186:3306/oss?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 7Tf88ga2pU
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 6000
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  http:
      multipart:
        maxFileSize: 200Mb
        maxRequestSize: 200Mb
server:
  port: 9091
  tomcat:
    max-threads: 1024
    uri-encoding: utf-8
    basedir: /home/tomcat-oss

upload:
  cache:
    file: /home/directory
#    file: E:\fgh\
    delimiter: /
    thumbnailWidth: 160
    thumbnailHeight: 160