package org.garen.oss.mybatis.mapper;

import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.garen.oss.mybatis.domain.File;
import org.garen.oss.mybatis.domain.FileQuery;

public interface FileMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    long countByExample(FileQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int deleteByExample(FileQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    List<File> selectByExample(FileQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    File selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int updateByExample(@Param("record") File record, @Param("example") FileQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Tue Sep 12 01:34:31 CST 2017
     */
    int updateByPrimaryKey(File record);
}